// <auto-generated />
using System;
using GoogleLoginToken;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoogleLoginToken.Migrations
{
    [DbContext(typeof(LoginContext))]
    partial class LoginContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("GoogleLoginToken.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Maximum")
                        .HasColumnType("int");

                    b.Property<int>("Minimum")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("OnlyAdminCanSet")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("GoogleLoginToken.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IdExterno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("IdValidador")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "Email_uniqueContraint")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GoogleLoginToken.UserPermiso", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int");

                    b.Property<int>("IdGrantedBy")
                        .HasColumnType("int")
                        .HasColumnName("GrantedById");

                    b.Property<int?>("PermisoId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("IdUser", "IdPermiso");

                    b.HasIndex("IdGrantedBy");

                    b.HasIndex("PermisoId");

                    b.HasIndex("UserId");

                    b.ToTable("PermisosUsuarios");
                });

            modelBuilder.Entity("GoogleLoginToken.UserPermiso", b =>
                {
                    b.HasOne("GoogleLoginToken.UserInfo", "GrantedBy")
                        .WithMany()
                        .HasForeignKey("IdGrantedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleLoginToken.Permiso", "Permiso")
                        .WithMany("Usuarios")
                        .HasForeignKey("PermisoId");

                    b.HasOne("GoogleLoginToken.UserInfo", "User")
                        .WithMany("Permisos")
                        .HasForeignKey("UserId");

                    b.Navigation("GrantedBy");

                    b.Navigation("Permiso");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoogleLoginToken.Permiso", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GoogleLoginToken.UserInfo", b =>
                {
                    b.Navigation("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
