// <auto-generated />
using System;
using GoogleLoginToken;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoogleLoginToken.Migrations
{
    [DbContext(typeof(LoginContext))]
    partial class LoginContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("GoogleLoginToken.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Maximum")
                        .HasColumnType("int");

                    b.Property<int>("Minimum")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("OnlyAdminCanSet")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("GoogleLoginToken.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IdExterno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("IdValidador")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "Email_uniqueContraint")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GoogleLoginToken.UserPermiso", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaGranted")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaRevoked")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GrantedById")
                        .HasColumnType("int");

                    b.Property<int?>("RevokedById")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PermisoId");

                    b.HasIndex("GrantedById");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RevokedById");

                    b.ToTable("PermisosUsuarios");
                });

            modelBuilder.Entity("GoogleLoginToken.UserPermiso", b =>
                {
                    b.HasOne("GoogleLoginToken.UserInfo", "GrantedBy")
                        .WithMany()
                        .HasForeignKey("GrantedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleLoginToken.Permiso", "Permiso")
                        .WithMany("Usuarios")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleLoginToken.UserInfo", "RevokedBy")
                        .WithMany()
                        .HasForeignKey("RevokedById");

                    b.HasOne("GoogleLoginToken.UserInfo", "User")
                        .WithMany("Permisos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrantedBy");

                    b.Navigation("Permiso");

                    b.Navigation("RevokedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoogleLoginToken.Permiso", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GoogleLoginToken.UserInfo", b =>
                {
                    b.Navigation("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
